package net.kevinmendoza.geoworldlibrary.geology.recursivegeology.cache;

import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.cache.Cache.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import com.flowpowered.math.vector.Vector2i;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.node.INode;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.prototype.IPrototype;
public class CacheTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(Cache.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Cache target = new Cache();
		assertThat(target, notNullValue());
	}

	@Test
	public void getMemberList_A$() throws Exception {
	}

	@Test
	public void getKeyList_A$() throws Exception {
		
	}

	@Test
	public void addKeyValuePair_A$Vector2i$INode() throws Exception {
	}

	@Test
	public void addNullValueToKey_A$Vector2i() throws Exception {
	}

	@Test
	public void getMissingNeighborKeys_A$List() throws Exception {
	}

	@Test
	public void getInternalRegionsFromKeyList_A$List$Vector2i() throws Exception {
	}

	@Test
	public void getExternalRegionsFromKeyList_A$List$Vector2i() throws Exception {
	}

	@Test
	public void getInternalRegions_A$Vector2i() throws Exception {
	}

	@Test
	public void getExternalRegions_A$Vector2i() throws Exception {
	}

	@Test
	public void getValue_A$Vector2i() throws Exception {
		
	}


}
