
package net.kevinmendoza.geoworldlibrary.geology.recursivegeology.node;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;

import org.junit.Test;

import com.flowpowered.math.vector.Vector2i;
import com.flowpowered.math.vector.Vector3i;

import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.IData;
public class MapTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(Map.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ICacheBuilder builder = null;
		Map target = new Map(builder);
		assertThat(target, notNullValue());
	}

	@Test
	public void getBaseData_A$Vector2i() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ICacheBuilder builder = null;
		Map target = new Map(builder);
		Vector2i vector2i = null;
		IData actual = target.getBaseData(vector2i);
		IData expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void getBaseData_A$Vector3i() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ICacheBuilder builder = null;
		Map target = new Map(builder);
		Vector3i vector3i = null;
		IData actual = target.getBaseData(vector3i);
		IData expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

}
