package net.kevinmendoza.geoworldlibrary.geology.recursivegeology.node;

import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.node.Node.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import com.flowpowered.math.vector.Vector2i;
import com.flowpowered.math.vector.Vector3i;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.DefaultDataFactory;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.EmptyDataFactory;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.GenerationData;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.IGeologyData;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.singleagedata.ISingularGeologyData;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.singleagedata.Surface;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.cache.INodeCache;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.factory.INodeFactory;
public class NodeTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(Node.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		
	}

	@Test
	public void convertToNode_A$() throws Exception {
		
	}

	@Test
	public void getName_A$() throws Exception {
		
	}

	@Test
	public void isLeaf_A$() throws Exception {
		
	}

	@Test
	public void getCenterDistance_A$Vector3i() throws Exception {
		
	}

	@Test
	public void getCenterDistance_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getPrototypeInfo_A$Vector3i() throws Exception {
		
	}

	@Test
	public void setInternalList_A$Collection() throws Exception {
		
	}

	@Test
	public void setExternalList_A$Collection() throws Exception {
		
	}

	@Test
	public void getRGBDebugAtCoordinates_A$Vector3i() throws Exception {
		
	}

	@Test
	public void loadNearbyNodes_A$GenerationData() throws Exception {
		
	}

	@Test
	public void primeLoadedObjects_A$GenerationData() throws Exception {
		
	}

	@Test
	public void primeGeneratedObjects_A$GenerationData() throws Exception {
		
	}

	@Test
	public void getPrototype3DData_A$ISingularGeologyData$Vector3i() throws Exception {
		
	}

	@Test
	public void getPrototype2DData_A$ISingularGeologyData$Vector2i() throws Exception {
		
	}

	@Test
	public void getExternalDecay_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getExternalDecay_A$Vector3i() throws Exception {
		
	}

	@Test
	public void getInternalDecay_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getInternalDecay_A$Vector3i() throws Exception {
		
	}

	@Test
	public void isInside_A$Vector2i() throws Exception {
		
	}

	@Test
	public void isInside_A$Vector3i() throws Exception {
		// TODO auto-generated by JUnit Helper.
		
	}

	@Test
	public void getRandomInternalPoint2i_A$() throws Exception {
		
	}

	@Test
	public void getRandomInternalPoint3i_A$() throws Exception {
		
	}

	@Test
	public void get2DGeologyData_A$ISingularGeologyData$Vector2i() throws Exception {
		
	}

	@Test
	public void get3DGeologyData_A$ISingularGeologyData$Vector3i() throws Exception {
		
	}

	@Test
	public void mergeData_A$ISingularGeologyData$Vector3i$HashSet() throws Exception {
		
	}

	@Test
	public void mergeData_A$ISingularGeologyData$Vector2i$HashSet() throws Exception {
		
	}

	@Test
	public void equals_A$Object() throws Exception {
		
	}

	@Test
	public void hashCode_A$() throws Exception {
	
	}

	@Test
	public void getStartingData_A$ISingularGeologyData() throws Exception {
		
	
	}

}
