package net.kevinmendoza.geoworldlibrary.geology.recursivegeology.prototype;

import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.prototype.NullPrototype.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;
import com.flowpowered.math.vector.Vector2i;
import com.flowpowered.math.vector.Vector3i;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.DefaultDataFactory;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.GenerationData;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.Order;
import net.kevinmendoza.geoworldlibrary.geology.compositerockdata.singleagedata.ISingularGeologyData;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.factory.AbstractPrototypeFactory;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.factory.INodeFactory;
import net.kevinmendoza.geoworldlibrary.geology.recursivegeology.node.INode;
import net.kevinmendoza.geoworldlibrary.proceduralgeneration.region.IRegion;
public class NullPrototypeTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(NullPrototype.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		
	}

	@Test
	public void getName_A$() throws Exception {
		
	}

	@Test
	public void isLeaf_A$() throws Exception {
		
	}

	@Test
	public void convertToNode_A$() throws Exception {
		
	}

	@Test
	public void isInside_A$Vector2i() throws Exception {
		
	}

	@Test
	public void isInside_A$Vector3i() throws Exception {
		
	}

	@Test
	public void getCenterDistance_A$Vector3i() throws Exception {
	
	}

	@Test
	public void getCenterDistance_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getRandomInternalPoint2i_A$() throws Exception {
		
	}

	@Test
	public void getRandomInternalPoint3i_A$() throws Exception {
		
	}

	@Test
	public void getExternalDecay_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getExternalDecay_A$Vector3i() throws Exception {
		
	}

	@Test
	public void loadNearbyNodes_A$GenerationData() throws Exception {
		
	}

	@Test
	public void primeLoadedObjects_A$GenerationData() throws Exception {
	
	}

	@Test
	public void get3DGeologyData_A$ISingularGeologyData$Vector3i() throws Exception {
		
	}

	@Test
	public void get2DGeologyData_A$ISingularGeologyData$Vector2i() throws Exception {
		
	}

	@Test
	public void getStartingData_A$ISingularGeologyData() throws Exception {
		
	}

	@Test
	public void getRGBDebugAtCoordinates_A$Vector3i() throws Exception {
		
	}

	@Test
	public void getLocationData_A$Vector3i() throws Exception {
		
	}

	@Test
	public void getInternalDecay_A$Vector2i() throws Exception {
		
	}

	@Test
	public void getInternalDecay_A$Vector3i() throws Exception {
	
	}

}
